#Write a program to input 8 numbers from the user and display all unique numbers(once)
s=set()
n=input("Enter number :")
s.add(int(n))
n=input("Enter number :")
s.add(int(n))
n=input("Enter number :")
s.add(int(n))
n=input("Enter number :")
s.add(int(n))
n=input("Enter number :")
s.add(int(n))
n=input("Enter number :")
s.add(int(n))
n=input("Enter number :")
s.add(int(n))
n=input("Enter number :")
s.add(int(n))
print(s)